services:
  mailframe-promo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: mailframe-promo:latest
    container_name: mailframe-promo
    hostname: mailframe-promo
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - mailframe-network
    healthcheck:
      test:
        [
          'CMD',
          'bun',
          '--eval',
          'fetch("http://localhost:3000/api/health").then(() => process.exit(0)).catch(() => process.exit(1))'
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M

  mailframe-docs:
    image: ghcr.io/codex-team/codex.docs:v2.2.3
    container_name: mailframe-docs
    hostname: mailframe-docs
    restart: always
    ports:
      - '3100:3100'
    environment:
      - APP_CONFIG_auth_password=${CODEX_AUTH_PASSWORD}
    volumes:
      - ./docs/uploads:/usr/src/app/uploads
      - ./docs/db:/usr/src/app/db
      - ./docs/docs-config.yaml:/usr/src/app/docs-config.yaml
    networks:
      - mailframe-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: mailframe-nginx
    hostname: mailframe-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    depends_on:
      mailframe-promo:
        condition: service_healthy
      mailframe-docs:
        condition: service_started
    networks:
      - mailframe-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  mailframe-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local
